// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNdgWfUQMR_oV4Zc7L-Dg7y2g9cRXe048',
    appId: '1:202870514058:web:4599f57b363f55d488a873',
    messagingSenderId: '202870514058',
    projectId: 'ders7-flutter-project-3',
    authDomain: 'ders7-flutter-project-3.firebaseapp.com',
    storageBucket: 'ders7-flutter-project-3.firebasestorage.app',
    measurementId: 'G-HC1GS982F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDUg3G1_3QdpdmnJjgQOMLDoNoZH4s95Y',
    appId: '1:202870514058:android:9dbf7e8ab3cc6dc488a873',
    messagingSenderId: '202870514058',
    projectId: 'ders7-flutter-project-3',
    storageBucket: 'ders7-flutter-project-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw0lCgcvysFJwCUb2sgHvtPi9Bwmlc1hc',
    appId: '1:202870514058:ios:281c21a75f9d72b388a873',
    messagingSenderId: '202870514058',
    projectId: 'ders7-flutter-project-3',
    storageBucket: 'ders7-flutter-project-3.firebasestorage.app',
    iosBundleId: 'com.example.ders7FlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw0lCgcvysFJwCUb2sgHvtPi9Bwmlc1hc',
    appId: '1:202870514058:ios:281c21a75f9d72b388a873',
    messagingSenderId: '202870514058',
    projectId: 'ders7-flutter-project-3',
    storageBucket: 'ders7-flutter-project-3.firebasestorage.app',
    iosBundleId: 'com.example.ders7FlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNdgWfUQMR_oV4Zc7L-Dg7y2g9cRXe048',
    appId: '1:202870514058:web:b00869686532b0c188a873',
    messagingSenderId: '202870514058',
    projectId: 'ders7-flutter-project-3',
    authDomain: 'ders7-flutter-project-3.firebaseapp.com',
    storageBucket: 'ders7-flutter-project-3.firebasestorage.app',
    measurementId: 'G-HYCNZ76ZRD',
  );
}
